from fastapi import APIRouter, Query
import requests
from pydantic import BaseModel
from typing import List
from openai import OpenAI

from utils.token import get_access_token
from utils.config import GROQ_API_KEY
from utils.spotify import (
    create_playlist,
    add_tracks_to_playlist,
    get_user_top_tracks,
    get_liked_songs,
    extract_song_info_from_liked_tracks
)

router = APIRouter()

@router.get("/me")
def get_user_profile(user_id: str = Query(...)):
    access_token = get_access_token(user_id)
    headers = {
        "Authorization": f"Bearer {access_token}"
    }

    response = requests.get("https://api.spotify.com/v1/me", headers=headers)

    if response.status_code == 401:
        return {"error": "Access token expired or invalid. Please re-authenticate."}

    return response.json()

# ──────────────────────────────────────────────
# 🧠 Groq LLM Test Route
# ──────────────────────────────────────────────
@router.get("/groq-test")
def test_groq():
    client = OpenAI(
        api_key=GROQ_API_KEY,
        base_url="https://api.groq.com/openai/v1"
    )

    response = client.chat.completions.create(
        model="llama3-8b-8192",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "What are 3 good songs for someone feeling nostalgic but happy?"}
        ]
    )

    return response.choices[0].message.content


@router.get("/create-test-playlist")
def make_test_playlist(user_id: str = Query(...)):
    access_token = get_access_token(user_id)

    playlist_id = create_playlist(
        user_id=user_id,
        access_token=access_token,
        playlist_name="VibeAI Test Playlist",
        description="Generated by VibeAI backend.",
        public=True
    )

    return {"message": "Playlist created!", "playlist_id": playlist_id}

class TrackRequest(BaseModel):
    playlist_id: str
    track_uris: List[str]

@router.post("/add-tracks")
def add_tracks_to_playlist_route(payload: TrackRequest, user_id: str = Query(...)):
    access_token = get_access_token(user_id)
    return add_tracks_to_playlist(
        playlist_id=payload.playlist_id,
        track_uris=payload.track_uris,
        access_token=access_token
    )

@router.get("/top-tracks")
def fetch_top_tracks(user_id: str = Query(...)):
    access_token = get_access_token(user_id)
    top_tracks = get_user_top_tracks(access_token)
    return top_tracks

@router.get("/liked-songs")
def liked_songs(user_id: str = Query(...)):
    access_token = get_access_token(user_id)
    liked_songs_data = get_liked_songs(access_token)
    song_descriptions = extract_song_info_from_liked_tracks(liked_songs_data)

    return {"songs": song_descriptions}

__all__ = ["router"]
